name: 'linkedin_pages_integration_tests'
version: '1.4.0'
profile: 'integration_tests'
config-version: 2

vars:
  linkedin_pages:
    linkedin_pages_organization_identifier: "linkedin_pages_organization_data"
    linkedin_pages_organization_ugc_post_identifier: "linkedin_pages_organization_ugc_post_data"
    linkedin_pages_share_statistic_identifier: "linkedin_pages_share_statistic_data"
    linkedin_pages_post_content_identifier: "linkedin_pages_post_content_data"
    linkedin_pages_ugc_post_history_identifier: "linkedin_pages_ugc_post_history_data"
    linkedin_pages_ugc_post_share_statistic_identifier: "linkedin_pages_ugc_post_share_statistic_data"
    linkedin_pages_organization_share_identifier: "linkedin_pages_organization_share_data"
    linkedin_pages_share_content_identifier: "linkedin_pages_share_content_data"
    linkedin_pages_share_history_identifier: "linkedin_pages_share_history_data"
    linkedin_pages_share_share_statistic_identifier: "linkedin_pages_share_share_statistic_data"
    linkedin_pages_schema: linkedin_pages_integration_tests

models:
  +schema: "linkedin_pages_{{ var('directed_schema','dev') }}"
  +persist_docs:
    relation: true
    columns: "{{ false if target.type in ('databricks') else true }}"

seeds:
  +docs:
    show: False
  +quote_columns: "{{ target.type == 'redshift' or var('fivetran_using_source_casing', false) }}"
  linkedin_pages_integration_tests: 
    linkedin_pages_ugc_post_share_statistic_data:
      +column_types:
        ugc_post_id: "{%- if target.type == 'bigquery' -%} INT64 {%- else -%} bigint {%- endif -%}"
    linkedin_pages_share_share_statistic_data:
      +column_types:
        share_id: "{%- if target.type == 'bigquery' -%} INT64 {%- else -%} bigint {%- endif -%}"
    linkedin_pages_organization_share_data:
      +column_types:
        share_id: "{%- if target.type == 'bigquery' -%} INT64 {%- else -%} bigint {%- endif -%}"
    linkedin_pages_share_content_data:
      +column_types:
        share_id: "{%- if target.type == 'bigquery' -%} INT64 {%- else -%} bigint {%- endif -%}"
    linkedin_pages_ugc_post_history_data:
      +column_types:
        created_actor: "{%- if target.type == 'bigquery' -%} STRING {%- elif target.type == 'databricks' -%} string {%- else -%} varchar {%- endif -%}"
        last_modified_actor: "{%- if target.type == 'bigquery' -%} STRING {%- elif target.type == 'databricks' -%} string {%- else -%} varchar {%- endif -%}"
    linkedin_pages_share_history_data:
      +column_types:
        id: "{%- if target.type == 'bigquery' -%} INT64 {%- else -%} bigint {%- endif -%}"
  
flags:
  send_anonymous_usage_stats: False
  use_colors: True